blank_issues_enabled: false
contact_links:
  - name: リンク サンプル
    url: https://example.com
    about: テンプレートの提示のほか、このようにリンクを提示することもできます
  - name: Issueとプルリクエストのテンプレートについて
    url: https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates
    about: Issueテンプレートについては、こちらをご参照ください。
