name: 検証報告（YAML）
description: 検証結果からissueを発行することを想定したテンプレート（YAMLによるフォーマット）
title: "[検証報告] ○○"
labels: ["verification-result"]
projects: [""]
assignees:
  - dzeyelid
body:
  - type: markdown
    attributes:
      value: |
        検証結果の記入をお願いします。
  - type: input
    id: date
    attributes:
      label: 検証日時
      description: 検証を実施した日時を入力してください
      placeholder: ○○年○月○日
    validations:
      required: true
  - type: dropdown
    id: result
    attributes:
      label: 検証結果
      description: 検証結果を選択してください
      options:
        - 不合格
        - 合格
      # default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## 検証内容
  - type: dropdown
    id: verify-item-001
    attributes:
      label: 検証項目1
      description: 複数選択できます
      multiple: true
      options:
        - 選択肢1
        - 選択肢2
        - 選択肢3
        - 選択肢4
    validations:
      required: true
  - type: checkboxes
    id: verify-item-002
    attributes:
      label: 検証項目2
      description: 
      options:
        - label: 路面は濡れていなかったか
        - label: 給油は満タンだったか
  - type: textarea
    id: verify-data
    attributes:
      label: 検証データ
      description: CSV形式で検証データを入力してください
      render: csv
      placeholder: |
        target,expected,actual
        speed,1.00,0.92
        vibration,0.01,0.81
  - type: markdown
    attributes:
      value: |
        ## 備考
  - type: textarea
    id: remarks
    attributes:
      label: 備考
      description: 上記に当てはまらない情報はこちらにご記入ください
      placeholder: 路面状態、天候など
      value: 特筆次項はありません。
  - type: markdown
    attributes:
      value: |
        ## 確認
  - type: checkboxes
    id: confirm
    attributes:
      label: 入力の確認
      description: 
      options:
        - label: 上記入力を確認の上、問題なければチェックしてください
          required: true
