name: サンプル1

on:
  issues:
    types:
      - opened

jobs:
  confirm:
    name: 内容確認
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-result.outputs.CHECK_RESULT }}
    steps:
      - name: debug
        run: echo ${GITHUB_CONTEXT} | jq
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
      - name: 結果を出力パラメータに設定する
        id: set-result
        run: |
          extracted_result=$(echo ${ISSUE_BODY} | sed -E 's/^.+### 検証結果\s+(合格|不合格).+$/\1/')
          [[ "$extracted_result" == "合格" ]] && check_result=true || check_result=false
          echo "CHECK_RESULT=${check_result}" >> $GITHUB_OUTPUT
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
  approve:
    name: 承認
    needs: confirm
    runs-on: ubuntu-latest
    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v4
      - name: Approveラベル付与
        run: gh issue view ${{ github.event.issue.id }}
        env:
          GH_TOKEN: ${{ github.token }}
