name: レポートを作成

on:
  issues:
    types:
      - opened

jobs:
  create-report:
    name: レポートを作成
    if: contains(github.event.issue.labels.*.name, 'report')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v4
      - name: レポート用のissueを作成
        run: |
          gh issue create \
            --body-file .github/workflows/issue-body-report.md \
            --title '[レポート]'
            
        env:
          GH_TOKEN: ${{ github.token }}      
